#!/bin/bash
# Builds loafcat into a .app bundle.
#
# Hand-rolled rather than SwiftPM's bundler because the app needs a specific
# Info.plist (LSUIElement) and an ad-hoc signature, and because assets must land in
# Contents/Resources. Command Line Tools is sufficient; full Xcode is not required.
set -euo pipefail
cd "$(dirname "$0")"

# A permission regression is cheap to catch here and expensive to catch in review.
./scripts/check-privacy.sh
# So is an update key the two ports disagree about, which nothing else would notice.
./scripts/check-update-key.sh

APP="build/LoafCat.app"
rm -rf build
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"

cat > "$APP/Contents/Info.plist" <<'PLIST'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleExecutable</key><string>LoafCat</string>
  <!-- Generated by tools/generate_icon.py from the mono theme's own parts, so the
       icon and the cat on the desktop cannot drift apart. -->
  <key>CFBundleIconFile</key><string>AppIcon</string>
  <!-- Locked permanently. Changing it later would invalidate every user's TCC
       grant with no migration path. -->
  <key>CFBundleIdentifier</key><string>dev.loafcat.app</string>
  <key>CFBundleName</key><string>loafcat</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleShortVersionString</key><string>0.2.0</string>
  <key>LSMinimumSystemVersion</key><string>13.0</string>
  <!-- Accessory app: no Dock icon, no Cmd-Tab. Also required to float over
       fullscreen apps. The menu bar item is therefore the ONLY way to quit. -->
  <key>LSUIElement</key><true/>
</dict>
</plist>
PLIST

# Globbed, not listed: a hardcoded file list means every new module breaks the
# build until someone remembers to add it here. main.swift goes last because it
# holds the top-level code.
SOURCES=$(find Sources/LoafCat -name '*.swift' ! -name 'main.swift' | sort)
swiftc -O \
  -o "$APP/Contents/MacOS/LoafCat" \
  $SOURCES \
  Sources/LoafCat/main.swift 2>&1 | grep -v "^$" || true

if [ ! -f "$APP/Contents/MacOS/LoafCat" ]; then
  echo "BUILD FAILED" >&2
  exit 1
fi

cp -R assets "$APP/Contents/Resources/assets"

# CFBundleIconFile is resolved against Resources/ directly, not against assets/.
# Regenerate with tools/generate_icon.py; it is committed so the build does not
# depend on iconutil being present.
cp assets/icon/AppIcon.icns "$APP/Contents/Resources/AppIcon.icns"

# The Claude Code hook script ships inside the bundle, but "Connect to Claude
# Code" copies it to ~/.loafcat/ before registering it. Pointing settings.json
# into the .app would break the moment the user moved or replaced the app, and a
# dead hook path reads to them as "Claude got slow".
cp -R hooks "$APP/Contents/Resources/hooks"
chmod +x "$APP/Contents/Resources/hooks/loafcat-hook.sh"

# Ad-hoc signature: Apple Silicon SIGKILLs a wholly unsigned binary. A persistent
# self-signed cert comes later -- it gives a stable Designated Requirement so any
# future permission grant survives updates.
codesign --force --sign - "$APP" 2>/dev/null

echo "built $APP"
